### ISSUE TITLE
update for rack v2 beta

### ISSUE THREAD

**Issue by jpnielsen** [LOGUNIVPM/VCVBook#5]
Hi,

I just tried to compile your modules for Rack v2 beta.

I changed the release to "2.0.0" in plugin.json, but got the following errors:

```
make

g++ -std=c++11 -Wsuggest-override  -fPIC -I../..//include -I../..//dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/ABC.cpp.o src/ABC.cpp
In file included from src/ABC.cpp:13:
src/ABC.hpp: In member function 'virtual void valueKnob::draw(const rack::widget::Widget::DrawArgs&)':
src/ABC.hpp:307:54: error: 'dirtyValue' was not declared in this scope; did you mean 'drawValue'?
  307 |                 snprintf(tbuf, sizeof(tbuf), "%.3G", dirtyValue);
      |                                                      ^~~~~~~~~~
      |                                                      drawValue
make: *** [../..//compile.mk:70: build/src/ABC.cpp.o] Error 1
```

Perhaps I'm too early, but will there be an update to your book and source code for VCVrack v2 ?

[latest rack v2 community edition build](https://community.vcvrack.com/t/rack-development-blog/5864/73)

[Migrating plugins from v1 to v2](https://vcvrack.com/manual/Migrate2)

best regards
Jens Peter Nielsen

**Comment by LOGUNIVPM** [comment]
Dear Jens,
thank you for the notification.
There is only a small fix required, that I haven't yet uploaded to the git repository. For the rest, the book is 100% compatible with Rack v2.
I haven't updated the git repo because Rack's default branch is still v1. When it will be v2 I will update my repository too.
In the meantime, if you want to try out my modules with Rack v2 you can patch manually the code of ABC.hpp as follows:

The offending function must be replaced with this updated version:

```
	void draw(const DrawArgs &args) override {
		char tbuf[128];

		ParamWidget::draw(args);

		engine::ParamQuantity* pq = getParamQuantity();
		if (pq) {
			float value = pq->getSmoothValue();
			snprintf(tbuf, sizeof(tbuf), "%.3G", value);
			drawValue(args, tbuf);
		}

	}
```

**Comment by jpnielsen** [comment]
Thank you.
